spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: create

server:
  servlet:
    session:
      cookie:
        path: /
        max-age: 2592000
        http-only: true
        same-site: none
        secure: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

aws:
  s3:
    bucket:
